const QUESTION = [
  {
    id: 1,
    question: 'What letter represents a race of extra-dimensional beings who possess immeasurable power over time, space, the laws of physics?',
    options: [
      'Z',
      'Q',
      'M',
      'X',
    ],
    answer: 'Q',
    flavorText: 'Q appeared in the first and last episodes of TNG\'s 7 season run and is responsible for introducing Starfleet to the Borg.',
  },
  {
    id: 2,
    question: 'In the two-part episode "Chain of Command", Captain Picard is imprisoned by the Cardassians and told there are five lights. How many lights are there in actuality?',
    options: [
      'There are TWO lights!',
      'There are THREE lights!',
      'There are FOUR lights!',
      'There are FIVE lights!',
    ],
    answer: 'There are FOUR lights!',
    flavorText: 'The tactic of overt gaslighting, used as a form of torture against Captain Picard, is a move straight out of Orwell\'s Nineteen Eighty-Four.',
  },
  {
    id: 3,
    question: 'What crew member relies on the holodeck to help overcome his crippling anxiety?',
    options: [
      'Reg Barclay',
      'Data',
      'Wesley Crusher',
      'Worf',
    ],
    answer: 'Reg Barclay',
    flavorText: 'Even though the crew didn\'t necessarily understand Reg, he still managed to save the ship and her crew on more than one occasion.',
  },
  {
    id: 4,
    question: 'In the episode "Parallels", there is some confusion about how Worf fared in a bat\'leth tournament. How did Worf do in the tournament?',
    options: [
      'Worf never attended the tournament',
      'Ninth Place',
      'Qapla’',
      'Champion Standing',
    ],
    answer: 'Champion Standing',
    flavorText: 'Worf appears in more episodes of the Star Trek franchise than any other character.',
  },
  {
    id: 5,
    question: 'What U.S. state is William Riker from?',
    options: [
      'Hawai`i',
      'Alaska',
      'Louisiana',
      'Michigan',
    ],
    answer: 'Alaska',
    flavorText: 'For an Alaskan, Riker sure loves jazz.',
  },
  {
    id: 6,
    question: 'While enjoying a holo-novel, Geordi and Data accidentally grant consciousness to what literary character?',
    options: [
      'Captain Ahab',
      'The Invisible Man',
      'Professor Moriarty',
      'Odysseus',
      ],
    answer: 'Professor Moriarty',
    flavorText: 'Data admires Sherlock Holmes in both reasoning capability and in musical skill.',
  },
  {
    id: 7,
    question: 'What is Worf\'s son\'s name?',
    options: [
      'Nicholas',
      'Benjamin',
      'Peter',
      'Alexander',
      ],
    answer: 'Alexander',
    flavorText: 'Isn\'t he the worst?',
  },
  {
    id: 8,
    question: 'In the episode "Inner Light", Captain Picard experiences a life in which space travel and Starfleet are just distant memories. What musical instrument does he acquire to remind him of this other life?',
    options: [
      'Flute',
      'Trombone',
      'Violin',
      'Piano',
      ],
    answer: 'Flute',
    flavorText: 'This episode is a defining moment in Captain Picard\s life.',
  },
  {
    id: 9,
    question: 'How many seasons was Tasha Yar on the show as a main character?',
    options: [
      'All seven',
      'Four',
      'Two',
      'Not even one',
      ],
    answer: 'Not even one',
    flavorText: 'Tasha Yar appears in later seasons via flashbacks and other cameos, however!',
  },
  {
    id: 10,
    question: 'The mysterious and wise bartender Guinan comes from a long-lived species of listeners. What is that species called?',
    options: [
      'Andorian',
      'Betazoid',
      'El Aurian',
      'The Founders',
    ],
    answer: 'El Aurian',
    flavorText: 'Another famous El Aurian is Dr. Soran, who appeared in the film Star Trek Generations.',
  },
];   
